### PR TITLE
Make the tracecode command and path match work

### PR DESCRIPTION
**Pull request by licodeli**
First step to make the tracecode work and the match feature work

### CODE REVIEW

**Comment by pombredanne** [comment]
@linexb thank you!

**Comment by licodeli** [comment]
@pombredanne  I have done some refinement job like cleaning up the useless code, imports etc. Please review. :)

**Comment by licodeli** [comment]
@pombredanne  The new changes of checksum match are done, please review, thanks. :)

**Comment by pombredanne** [comment]
Tell me when this is ready to review

**Review by pombredanne — APPROVED** [review]
Looking good! thanks. Merging

**Pull request merged**
